version: 1.2
tools:
  - subclass: CWL
    primaryDescriptorPath: workflows/strainGE_PE.wdl
    testParameterFiles: /test/strainGE_PE.json
    authors:
      - name: Marco Teixeira
        email: mcarvalh@broadinstitute.org